// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents

ExchangeRateService.getLatestRates();

// Datetime dt = ExchangeRateWrapper.processDateTimeString('Sat, 22 Mar 2025 00:00:01 +0000');
// System.debug(dt);